zookeeper:
  image: eventuateio/eventuateio-local-zookeeper:0.12.1
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888

kafka:
  image: eventuateio/eventuateio-local-kafka:0.12.1
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181

cdcservice:
  image: eventuateio/eventuateio-local-cdc-service:0.12.1
  ports:
    - "8099:8080"
  links:
    - eventuatedb
    - kafka
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://eventuatedb/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword

consoleserver:
  image: eventuateio/eventuateio-local-console:0.12.1
  links:
    - eventuatedb
    - zookeeper
  ports:
    - "8085:8080"
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://eventuatedb/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    DEBUG: kafka-node:*

eventuatedb:
  image: eventuateio/eventuateio-local-mysql:0.10.0
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw

ermpdb:
  build: ./mysql
  ports:
    - 4306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw

ermpservice:
  build: ./ermp-service/
  restart: unless-stopped
  ports:
    - "8080:8080"
  links:
    - ermpdb
    - eventuatedb
    - kafka
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://ermpdb/ermp
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_DATASOURCE_URL: jdbc:mysql://eventuatedb/eventuate
    EVENTUATELOCAL_DATASOURCE_USERNAME: mysqluser
    EVENTUATELOCAL_DATASOURCE_PASSWORD: mysqlpw
    EVENTUATELOCAL_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword

apigateway:
  build: ./api-gateway-service2/
  restart: unless-stopped
  ports:
    - "8081:8080"
  links:
    - ermpservice
  environment:
    ERMP_SERVICE_HOST: ermpservice